In [2]:
import numpy as pm

In [3]:
l=[1,2,3,4,5]

In [4]:
pm.array(l)

array([1, 2, 3, 4, 5])

In [5]:
ar = pm.array(l)

In [6]:
type(ar)

numpy.ndarray

In [7]:
pm.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [8]:
b = pm.matrix(l)

In [9]:
b

matrix([[1, 2, 3, 4, 5]])

In [10]:
pm.asanyarray(b)

matrix([[1, 2, 3, 4, 5]])

In [11]:
a =pm.array(l)

In [12]:
a

array([1, 2, 3, 4, 5])

In [13]:
c =a

In [14]:
c

array([1, 2, 3, 4, 5])

In [15]:
c[0]

1

In [16]:
c[0]=100

In [17]:
c

array([100,   2,   3,   4,   5])

In [18]:
a

array([100,   2,   3,   4,   5])

In [19]:
d = pm.copy(a)

In [20]:
d

array([100,   2,   3,   4,   5])

In [21]:
a[1]=700

In [22]:
c

array([100, 700,   3,   4,   5])

In [23]:
a

array([100, 700,   3,   4,   5])

In [24]:
d

array([100,   2,   3,   4,   5])

In [25]:
pm.fromfunction(lambda i,j,:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [26]:
pm.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [27]:
iterable =(i*i for i in range(5))

In [28]:
pm.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [29]:
pm.fromstring('22',sep =',')

array([22.])

In [30]:
pm.fromstring('4,5',sep = ',')

array([4., 5.])

In [31]:
#numpy -Data-Types.

In [32]:
l =[1,2,3,4,6,7]

In [33]:
ar =pm.array(l)

In [34]:
ar

array([1, 2, 3, 4, 6, 7])

In [35]:
ar.ndim

1

In [36]:
ar2=pm.array([[1,2,3],[5,6,7]])

In [37]:
ar2

array([[1, 2, 3],
       [5, 6, 7]])

In [38]:
ar2.ndim

2

In [39]:
ar2.size

6

In [40]:
ar.size

6

In [41]:
ar.shape

(6,)

In [42]:
ar2.shape

(2, 3)

In [43]:
ar.dtype

dtype('int64')

In [44]:
ar2.dtype

dtype('int64')

In [45]:
ar22 = pm.array([(1.5,45,66,),(22,45,47)])

In [46]:
ar22

array([[ 1.5, 45. , 66. ],
       [22. , 45. , 47. ]])

In [47]:
ar22.dtype

dtype('float64')

In [48]:
range(5)

range(0, 5)

In [49]:
len(range(5))

5

In [50]:
list(range(5))

[0, 1, 2, 3, 4]

In [51]:
pm.arange(2.3,5.6,)

array([2.3, 3.3, 4.3, 5.3])

In [52]:
list(pm.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [53]:
pm.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [54]:
pm.zeros((4,6,8))

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.,

In [55]:
ar4 =pm.zeros((4,6,8))

In [56]:
ar4.ndim

3

In [57]:
ar4

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.,

In [58]:
pm.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [59]:
pm.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [60]:
on=pm.ones((3,4,5))

In [61]:
on*2

array([[[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]]])

In [62]:
pm.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [63]:
pm.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [64]:
pm.linspace(2,4, 20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [65]:
pm.logspace(2,5,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [66]:
pm.logspace(2,5,10,base= 3)


array([  9.        ,  12.98024613,  18.72075441,  27.        ,
        38.9407384 ,  56.16226322,  81.        , 116.82221519,
       168.48678967, 243.        ])

In [67]:
pm.random.randn(3,4)

array([[-1.71506276,  0.45651537,  1.20435214,  1.56657928],
       [ 0.71784736, -0.12491467, -2.33920235,  0.45135093],
       [ 0.06531679,  0.79783482, -2.33464891, -0.02717556]])

In [68]:
arr=pm.random.randn(3,4)

In [69]:
import pandas as pd

In [70]:
pd.DataFrame(arr)

0         1         2         3
0  1.755747 -0.425289  0.441367 -1.394640
1 -0.117586  0.305203 -0.798218  0.477902
2 -0.448707 -0.793935 -0.627132 -0.985593

In [71]:
pm.random.rand(3,4)

array([[0.1257151 , 0.15302681, 0.7024879 , 0.57610763],
       [0.21477004, 0.06557173, 0.89619648, 0.26276479],
       [0.13756789, 0.60001483, 0.21159596, 0.82910391]])

In [72]:
pm.random.randint(1,110,(300,400))

array([[ 99,  64,  72, ...,  54,  29,  66],
       [ 21,  25, 103, ...,  88,  71,  21],
       [108,  72,  70, ...,   7,  77, 104],
       ...,
       [ 81,  74,  42, ...,   8,  20,  49],
       [ 43,  73,  77, ...,  23,  71, 108],
       [ 61,   2,  70, ...,  17,  26,  52]])

In [80]:
 s=pm.random.randint(1,11,(30,40))

In [81]:
pd.DataFrame(s)

0   1   2   3   4   5   6   7   8   9   ...  30  31  32  33  34  35  36  \
0    5   3   7   6   4   6   5   3  10   9  ...   4   8   1   3   6   7   8   
1    2   5   1   5   4   9   8   5  10   8  ...   3   3  10   8   2  10   5   
2    4   8   4  10  10  10   7   7   2   4  ...   2   5   4  10   2  10   9   
3    1   5   4   1   4  10   9   6   2   9  ...   8   2   8   6  10   1   9   
4    3   9   9   2  10   6   9   6   3  10  ...   6   9   4   7   6  10  10   
5    6   7   7   6   3   8   2   4   3   6  ...   8   2   7   3  10   9  10   
6    1   9   4   5   9   4   4   7   5   5  ...   2   4   8   5   7   8   5   
7    3   4   8   6  10   9   6   7   3   6  ...   5   2   3   7   5   6   9   
8    8   9   3   1   2  10   4   1   7   6  ...   6   9   1   5  10   4   7   
9    7   8   2   3   4   7   5   1   4   9  ...   4   9   5   2   9   4   8   
10  10   7   5   2   1   6   4   5   1   2  ...   8   6  10   7  10   7   5   
11   3   3   5   9   3   8   8  10   1   4  ...   5  10   2   5   8   4   9   
12   4  10   4   6   8   4   1   8   9   6  ...  10   8   8   9   9  10   9   
13   5   2   3   8   4   1   4   1   3   7  ...   2   3   6   6   9   2   5   
14   7   7   6   6   1   3  10   7   8   9  ...  10   7   9   6   6   6   4   
15   9   9   4   3   4   4   7   7   5  10  ...   3   3   8   2   7  10   9   
16   8   5   4   3   5   2   1   2   6   7  ...  10   6   9   8   1   7   1   
17  10   3   9   7   4   3   4   1  10  10  ...   5   7   4   3   5   5   8   
18   4  10   6   5   4   1  10   9   6   5  ...  10   2   3  10   3   9   6   
19   6   2   9   2   4  10   5   8   4   6  ...   5   2   9   7   8   5   9   
20   1   7   4   7   7   3   1   9   3   8  ...   3  10   7   8   4   6   7   
21   2  10   8  10   1   3   3   6   6   5  ...   1   6   2   7   9   3   9   
22   3   2   6   3  10   7   4   9   9   3  ...   3   4   7   9  10   9   7   
23   6   5  10  10   6  10   2   8   2   7  ...  10   5   7   7   3   1   3   
24   5  10   7   8   7   2   6   1   7   6  ...   4   6   9   9  10  10   7   
25   3   4   6   1   3   9   5   6   2   6  ...   4   6   2   5   6   8   5   
26   5   4   7   5   6   4   3   1   4   7  ...   5   6   7   7   4   9   6   
27   4   7   8   9   8   2  10   6   8   8  ...   2   8   2   6   7   8   7   
28   7   5   4  10   2   4   5   4   1   4  ...   1   4   3   3   5   9   7   
29   2   5   2   9   2   6   8   8   2   6  ...   7   4   5   1   7  10   6   

    37  38  39  
0   10   4   6  
1    5  10   9  
2    7  10   9  
3    2   5   8  
4    5   2   8  
5    1   1   7  
6    5   4   5  
7    9   8   8  
8    8   8   7  
9    8   3   9  
10   3  10   6  
11   4   4   9  
12   9   3   8  
13   1   9   6  
14   4   7   3  
15   2   7   4  
16   1   1   6  
17   9   3   3  
18   4  10  10  
19   9   7   3  
20   9   5   1  
21   3   2   7  
22   5  10   5  
23   7   9   5  
24   3  10   4  
25   9  10   2  
26  10   1   8  
27   9  10  10  
28   9   5   3  
29   2   1   6  

[30 rows x 40 columns]

In [75]:
pd.DataFrame(s).to_csv('data.csv')

In [76]:
arr = pm.random.rand(3,4)

In [77]:
arr

array([[0.03376013, 0.11045409, 0.60150286, 0.18440117],
       [0.82121304, 0.89868411, 0.80444563, 0.34868882],
       [0.85899891, 0.78373384, 0.02327509, 0.32942859]])

In [90]:
arr.reshape(6,2)

array([[0.03376013, 0.11045409],
       [0.60150286, 0.18440117],
       [0.82121304, 0.89868411],
       [0.80444563, 0.34868882],
       [0.85899891, 0.78373384],
       [0.02327509, 0.32942859]])

In [91]:
arr1=arr.reshape(6,2)

In [93]:
arr1[1][1]

0.1844011652268327

In [94]:
arr1[1][1]

0.1844011652268327

In [96]:
arr1[2:5]

array([[0.82121304, 0.89868411],
       [0.80444563, 0.34868882],
       [0.85899891, 0.78373384]])

In [97]:
arr1[2:5,1]

array([0.89868411, 0.34868882, 0.78373384])

In [98]:
pm.random.randint(1,100,(5,5))

array([[35, 68,  9, 70, 98],
       [29, 36, 99, 70,  4],
       [62, 76, 19, 77, 54],
       [76, 66, 20, 18, 88],
       [72, 35, 42, 27, 38]])

In [99]:
arr=pm.random.randint(1,100,(5,5))

In [101]:
arr>50

array([[ True,  True, False, False, False],
       [ True, False, False, False,  True],
       [False, False, False,  True,  True],
       [False, False,  True,  True, False],
       [ True,  True,  True,  True, False]])

In [102]:
arr[arr>50]

array([82, 95, 85, 72, 89, 72, 99, 79, 64, 76, 71, 69])

In [103]:
arr

array([[82, 95, 49, 40,  2],
       [85,  6, 50, 14, 72],
       [33, 28, 38, 89, 72],
       [43,  9, 99, 79, 38],
       [64, 76, 71, 69,  2]])

In [104]:
arr[2:4,]

array([[33, 28, 38, 89, 72],
       [43,  9, 99, 79, 38]])

In [106]:
arr[2:4,[1,2]]

array([[28, 38],
       [ 9, 99]])

In [108]:
arr[0][0]

82

In [109]:
arr[0][0]=200000

In [110]:
arr

array([[200000,     95,     49,     40,      2],
       [    85,      6,     50,     14,     72],
       [    33,     28,     38,     89,     72],
       [    43,      9,     99,     79,     38],
       [    64,     76,     71,     69,      2]])

In [ ]:
arr[0][0]

In [112]:
pm.random.randint(1,3,(3,3))

array([[2, 2, 1],
       [1, 2, 1],
       [2, 2, 2]])

In [113]:
arr1=pm.random.randint(1,3,(3,3))

In [120]:
arr2=pm.random.randint(1,3,(3,3))

In [115]:
arr1

array([[2, 1, 1],
       [1, 2, 2],
       [1, 2, 1]])

In [119]:
arr2

array([[4, 4, 3],
       [3, 3, 2],
       [4, 2, 3]])

In [117]:
arr1+arr2

array([[3, 3, 3],
       [3, 3, 4],
       [2, 4, 3]])

In [121]:
arr1/arr2

array([[2. , 0.5, 1. ],
       [0.5, 2. , 2. ],
       [0.5, 1. , 1. ]])

In [122]:
arr1*arr2

array([[2, 2, 1],
       [2, 2, 2],
       [2, 4, 1]])

In [123]:
arr1

array([[2, 1, 1],
       [1, 2, 2],
       [1, 2, 1]])

In [124]:
arr2

array([[1, 2, 1],
       [2, 1, 1],
       [2, 2, 1]])

In [125]:
arr1@arr2

array([[6, 7, 4],
       [9, 8, 5],
       [7, 6, 4]])

In [126]:
arr3=pm.random.randint(1,3,(5,3))

In [127]:
arr3

array([[2, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 2, 1],
       [1, 1, 2]])

In [129]:
arr3+15

array([[17, 16, 16],
       [16, 16, 16],
       [16, 16, 16],
       [16, 17, 16],
       [16, 16, 17]])

In [130]:
arr3**2

array([[4, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 4, 1],
       [1, 1, 4]])

In [ ]:
#pythen - Broadcasting

In [132]:
pm.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [133]:
pm.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [134]:
q=pm.zeros((4,4))

In [135]:
q

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [136]:
pm.array([1,2,3,4,])

array([1, 2, 3, 4])

In [137]:
s=pm.array([1,2,3,4,])

In [138]:
q+s

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [139]:
s.T

array([1, 2, 3, 4])

In [143]:
col=pm.array([[1,2,3,4,]])

In [144]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [145]:
col

array([[1, 2, 3, 4]])

In [148]:
col.T + s

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

In [149]:
s

array([1, 2, 3, 4])

In [150]:
pm.random.randint(1,5,(3,4))

array([[2, 1, 4, 1],
       [3, 3, 2, 3],
       [4, 4, 4, 1]])

In [151]:
 arrr1=pm.random.randint(1,5,(3,4))

In [152]:
arrr1

array([[1, 4, 2, 4],
       [3, 2, 4, 3],
       [4, 4, 1, 3]])

In [153]:
pm.sqrt(arrr1)

array([[1.        , 2.        , 1.41421356, 2.        ],
       [1.73205081, 1.41421356, 2.        , 1.73205081],
       [2.        , 2.        , 1.        , 1.73205081]])

In [154]:
pm.sort(arrr1)

array([[1, 2, 4, 4],
       [2, 3, 3, 4],
       [1, 3, 4, 4]])

In [156]:
pm.exp(arrr1)

array([[ 2.71828183, 54.59815003,  7.3890561 , 54.59815003],
       [20.08553692,  7.3890561 , 54.59815003, 20.08553692],
       [54.59815003, 54.59815003,  2.71828183, 20.08553692]])

In [158]:
pm.log10(arrr1)

array([[0.        , 0.60205999, 0.30103   , 0.60205999],
       [0.47712125, 0.30103   , 0.60205999, 0.47712125],
       [0.60205999, 0.60205999, 0.        , 0.47712125]])