In [3]:
import numpy as np

In [4]:
np.random.randint(1,5,(3,4))

array([[2, 2, 4, 1],
       [2, 3, 1, 1],
       [3, 4, 2, 4]])

In [5]:
arr = np.random.randint(1,5,(3,4))

In [6]:
arr.reshape(2,6)

array([[3, 1, 3, 1, 3, 1],
       [3, 4, 4, 3, 2, 3]])

In [7]:
arr.flatten()

array([3, 1, 3, 1, 3, 1, 3, 4, 4, 3, 2, 3])

In [11]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [12]:
arr1 =np.array([1,2,3,4,5])

In [13]:
arr1.ndim

1

In [16]:
np.expand_dims(arr1,axis =1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [17]:
np.expand_dims(arr1,axis = 0)

array([[1, 2, 3, 4, 5]])

In [18]:
arr

array([[3, 1, 3, 1],
       [3, 1, 3, 4],
       [4, 3, 2, 3]])

In [19]:
np.squeeze(arr)

array([[3, 1, 3, 1],
       [3, 1, 3, 4],
       [4, 3, 2, 3]])

In [20]:
np.array([[1],[2],[3]])

array([[1],
       [2],
       [3]])

In [21]:
data = np.array([[1],[2],[3]])

In [25]:
np.squeeze(data)

array([1, 2, 3])

In [26]:
arr1

array([1, 2, 3, 4, 5])

In [32]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [36]:
np.roll(arr1,2)

array([4, 5, 1, 2, 3])

In [34]:
arr1

array([1, 2, 3, 4, 5])

In [35]:
np.roll(arr1,3)

array([3, 4, 5, 1, 2])

In [37]:
np.roll(arr1,4)

array([2, 3, 4, 5, 1])

In [38]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [ ]:
#Pythen Binary Operators

In [39]:
np.random.randint(1,10,(3,4))

array([[8, 8, 5, 1],
       [8, 9, 2, 8],
       [1, 6, 4, 4]])

In [40]:
arr2 = np.random.randint(1,10,(3,4))

In [41]:
arr2

array([[2, 2, 8, 7],
       [7, 5, 7, 8],
       [2, 5, 1, 9]])

In [44]:
arr1 

array([1, 2, 3, 4, 5])

In [45]:
arr1 = np.random.randint(1,10,(3,4))

In [46]:
arr1+arr2

array([[ 9,  5, 12,  8],
       [ 9, 13, 16, 16],
       [11, 11,  2, 13]])

In [47]:
arr1

array([[7, 3, 4, 1],
       [2, 8, 9, 8],
       [9, 6, 1, 4]])

In [49]:
arr1/arr2

array([[3.5       , 1.5       , 0.5       , 0.14285714],
       [0.28571429, 1.6       , 1.28571429, 1.        ],
       [4.5       , 1.2       , 1.        , 0.44444444]])

In [50]:
arr1-arr2

array([[ 5,  1, -4, -6],
       [-5,  3,  2,  0],
       [ 7,  1,  0, -5]])

In [51]:
arr1*arr2

array([[14,  6, 32,  7],
       [14, 40, 63, 64],
       [18, 30,  1, 36]])

In [52]:
arr1%arr2

array([[1, 1, 4, 1],
       [2, 3, 2, 0],
       [1, 1, 0, 4]])

In [53]:
arr1**arr2

array([[      49,        9,    65536,        1],
       [     128,    32768,  4782969, 16777216],
       [      81,     7776,        1,   262144]])

In [54]:
arr1&arr2

array([[2, 2, 0, 1],
       [2, 0, 1, 8],
       [0, 4, 1, 0]])

In [55]:
~arr1

array([[ -8,  -4,  -5,  -2],
       [ -3,  -9, -10,  -9],
       [-10,  -7,  -2,  -5]])

In [56]:
arr1|arr2

array([[ 7,  3, 12,  7],
       [ 7, 13, 15,  8],
       [11,  7,  1, 13]])

In [57]:
arr1>arr2

array([[ True,  True, False, False],
       [False,  True,  True, False],
       [ True,  True, False, False]])

In [ ]:
#Numpy String Functions.

In [58]:
np.array(['sudhir','lodhi'])

array(['sudhir', 'lodhi'], dtype='<U6')

In [59]:
arr3 = np.array(['sudhir','lodhi'])

In [60]:
arr3

array(['sudhir', 'lodhi'], dtype='<U6')

In [61]:
np.char.upper(arr3)

array(['SUDHIR', 'LODHI'], dtype='<U6')

In [65]:
np.char.title(arr3)

array(['Sudhir', 'Lodhi'], dtype='<U6')

In [67]:
np.char.capitalize(arr3)

array(['Sudhir', 'Lodhi'], dtype='<U6')

In [ ]:
#Pythen Mathematical Function

In [68]:
arr1

array([[7, 3, 4, 1],
       [2, 8, 9, 8],
       [9, 6, 1, 4]])

In [70]:
np.sin(arr1)

array([[ 0.6569866 ,  0.14112001, -0.7568025 ,  0.84147098],
       [ 0.90929743,  0.98935825,  0.41211849,  0.98935825],
       [ 0.41211849, -0.2794155 ,  0.84147098, -0.7568025 ]])

In [72]:
np.cos(arr1)

array([[ 0.75390225, -0.9899925 , -0.65364362,  0.54030231],
       [-0.41614684, -0.14550003, -0.91113026, -0.14550003],
       [-0.91113026,  0.96017029,  0.54030231, -0.65364362]])

In [76]:
np.tan(arr1)

array([[ 0.87144798, -0.14254654,  1.15782128,  1.55740772],
       [-2.18503986, -6.79971146, -0.45231566, -6.79971146],
       [-0.45231566, -0.29100619,  1.55740772,  1.15782128]])

In [77]:
np.tanh(arr1)

array([[0.99999834, 0.99505475, 0.9993293 , 0.76159416],
       [0.96402758, 0.99999977, 0.99999997, 0.99999977],
       [0.99999997, 0.99998771, 0.76159416, 0.9993293 ]])

In [78]:
np.log(arr1)

array([[1.94591015, 1.09861229, 1.38629436, 0.        ],
       [0.69314718, 2.07944154, 2.19722458, 2.07944154],
       [2.19722458, 1.79175947, 0.        , 1.38629436]])

In [79]:
np.log10(arr1)

array([[0.84509804, 0.47712125, 0.60205999, 0.        ],
       [0.30103   , 0.90308999, 0.95424251, 0.90308999],
       [0.95424251, 0.77815125, 0.        , 0.60205999]])

In [80]:
np.exp(arr1)

array([[1.09663316e+03, 2.00855369e+01, 5.45981500e+01, 2.71828183e+00],
       [7.38905610e+00, 2.98095799e+03, 8.10308393e+03, 2.98095799e+03],
       [8.10308393e+03, 4.03428793e+02, 2.71828183e+00, 5.45981500e+01]])

In [81]:
np.sqrt(arr1)

array([[2.64575131, 1.73205081, 2.        , 1.        ],
       [1.41421356, 2.82842712, 3.        , 2.82842712],
       [3.        , 2.44948974, 1.        , 2.        ]])

In [84]:
np.power(arr1,3)

array([[343,  27,  64,   1],
       [  8, 512, 729, 512],
       [729, 216,   1,  64]])

In [85]:
np.std(arr1)

2.9107081994288304

In [87]:
np.var(arr1)

8.472222222222223

In [88]:
np.min(arr1)

1

In [90]:
np.max(arr1)

9

In [91]:
arr1

array([[7, 3, 4, 1],
       [2, 8, 9, 8],
       [9, 6, 1, 4]])