In [ ]:
#Sort Search & Counting Functions.

In [3]:
import numpy as np

In [4]:
np.array([2,3,45,66,77,8,9,6,4,2,1,])

array([ 2,  3, 45, 66, 77,  8,  9,  6,  4,  2,  1])

In [5]:
ar = np.array([2,3,45,66,77,8,9,6,4,2,1,])

In [6]:
ar

array([ 2,  3, 45, 66, 77,  8,  9,  6,  4,  2,  1])

In [7]:
np.sort(ar)

array([ 1,  2,  2,  3,  4,  6,  8,  9, 45, 66, 77])

In [8]:
np.searchsorted(ar,99)

11

In [9]:
np.array([0,0,0,0,0,0,0,2,3,1,3,1,5,6,7,])

array([0, 0, 0, 0, 0, 0, 0, 2, 3, 1, 3, 1, 5, 6, 7])

In [13]:
ar= np.array([0,1,0,3,0,0,2,0,0,0,2,3,1,3,1,5,6,7,])

In [14]:
np.count_nonzero(ar)

11

In [17]:
np.where(ar>3)

(array([15, 16, 17]),)

In [21]:
np.extract(ar>6,ar)

array([7])

In [22]:
np.extract(ar>2,ar)

array([3, 3, 3, 5, 6, 7])

In [ ]:
#Numpy - Byte Swapping


In [24]:
ar

array([0, 1, 0, 3, 0, 0, 2, 0, 0, 0, 2, 3, 1, 3, 1, 5, 6, 7])

In [34]:
ar.byteswap()

array([3963167672086036480,   72057594037927936,                   0,
        216172782113783808,                   0,                   0,
        144115188075855872,                   0,                   0,
                         0,  144115188075855872,  216172782113783808,
         72057594037927936,  216172782113783808,   72057594037927936,
        360287970189639680,  432345564227567616,  504403158265495552])

In [26]:
a = np.copy(ar)

In [27]:
b = ar.view()

In [28]:
ar

array([0, 1, 0, 3, 0, 0, 2, 0, 0, 0, 2, 3, 1, 3, 1, 5, 6, 7])

In [29]:
b[0] = 55

In [30]:
ar

array([55,  1,  0,  3,  0,  0,  2,  0,  0,  0,  2,  3,  1,  3,  1,  5,  6,
        7])

In [31]:
arr= np.array([5,1,5,6,7,])

In [33]:
arr.byteswap()

array([360287970189639680,  72057594037927936, 360287970189639680,
       432345564227567616, 504403158265495552])

In [35]:
a = np.copy(arr)

In [36]:
b =ar.view()

In [37]:
b

array([55,  1,  0,  3,  0,  0,  2,  0,  0,  0,  2,  3,  1,  3,  1,  5,  6,
        7])

In [38]:
b [3] = 111

In [39]:
b

array([ 55,   1,   0, 111,   0,   0,   2,   0,   0,   0,   2,   3,   1,
         3,   1,   5,   6,   7])

In [ ]:
#Numpy Matrix Library.

In [40]:
import numpy.matlib as  nm

In [44]:
nm.zeros((5,3))

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [43]:
nm.ones((3,5))

matrix([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [45]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
#Numpy  Linear Algebra

In [46]:
arr1 = np.random.randint([[2,3],[4,5]])

In [47]:
arr1

array([[1, 0],
       [1, 1]])

In [49]:
arr2 = np.random.randint([[5,3],[2,5]])

In [50]:
arr2

array([[1, 1],
       [1, 1]])

In [51]:
np.dot(arr1,arr2)

array([[1, 1],
       [2, 2]])

In [52]:
arr1@arr2

array([[1, 1],
       [2, 2]])